### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by StrategyLLC** [aaemnnosttv/wp-cli-dotenv-command#24]
Hello! We install our sites using WP CLI which has been empowered by your wonderful addon. We also use Bedrock so our sites are managed using Composer. We want to upgrade to PHP 8, but the versioning of your package does not allow the dependency to resolve. Here is the error:

- Root composer.json requires aaemnnosttv/wp-cli-dotenv-command ^2.0 -> satisfiable by aaemnnosttv/wp-cli-dotenv-command[v2.0.0].
- aaemnnosttv/wp-cli-dotenv-command v2.0.0 requires php ^5.6 | ^7.0 -> your php version (8.0.5) does not satisfy that requirement.

Is there any way we can get PHP8 compatibility in this package?

**Comment by aaemnnosttv** [comment]
Hi there! Thanks for the request. I haven't updated this in a while but of course want to be sure it always supports the latest version of PHP. With that said, you're right that updating the `composer.json` to allow for installing on PHP 8 is a trivial change to make but it required a fair amount of other changes to allow for it to continue to run in CI. It's all updated now though and didn't require any changes to the command itself so we can consider this done 😄  (See #25)

However, you might find it difficult to upgrade the command since the command is present in the official wp-cli package index which is not really maintained anymore and it still references an outdated version of the command 😢 

I'll see about getting this resolved next as it's a problem that affects my other command packages as well.

It is possible to install/upgrade, you just need to use Composer directly (after removing the wp-cli package index from the list of composer repos in your `~/.wp-cli/packages/composer.json`).

Cheers!
